//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Test_ScenarioEntities : DbContext
    {
        public Test_ScenarioEntities()
            : base("name=Test_ScenarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HISTORY> HISTORies { get; set; }
        public virtual DbSet<HISTORY_RATES> HISTORY_RATES { get; set; }
        public virtual DbSet<INCOME> INCOMEs { get; set; }
        public virtual DbSet<MASTER> MASTERs { get; set; }
        public virtual DbSet<MORTGAGE> MORTGAGEs { get; set; }
        public virtual DbSet<RATE> RATES { get; set; }
        public virtual DbSet<SECURITIZATION> SECURITIZATIONs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VALUATION> VALUATIONs { get; set; }
    
        public virtual ObjectResult<Get_CPB_Vs_OPB_Result> Get_CPB_Vs_OPB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_CPB_Vs_OPB_Result>("Get_CPB_Vs_OPB");
        }
    }
}
