//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_RATES
    {
        public string M_PoolID { get; set; }
        public string M_LoanID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string CurrentRateType { get; set; }
        public Nullable<double> CurrentInterestRate { get; set; }
        public Nullable<double> CurrentDTI { get; set; }
        public Nullable<double> CurrentLTFV { get; set; }
    
        public virtual RATE RATE { get; set; }
    }
}
