//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public string M_PoolID { get; set; }
        public string M_LoanID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<double> CurrentPrincipalBalance { get; set; }
        public Nullable<double> CurrentLTV { get; set; }
        public Nullable<double> LoanAge { get; set; }
        public string CurrentPropertyVal { get; set; }
        public Nullable<double> Savings { get; set; }
        public Nullable<double> CurrentIndexedLTV { get; set; }
        public Nullable<double> DelinquencyStatus { get; set; }
        public Nullable<decimal> BorrowerExposure { get; set; }
        public Nullable<int> NoBorrowers { get; set; }
    }
}
