//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORTGAGE
    {
        public string M_PoolID { get; set; }
        public string M_LoanID { get; set; }
        public string BTLStatus { get; set; }
        public string RepaymentType { get; set; }
        public string SecondLien { get; set; }
    
        public virtual MASTER MASTER { get; set; }
    }
}
