//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITIZATION
    {
        public string M_PoolID { get; set; }
        public string M_LoanID { get; set; }
        public Nullable<double> LifetimeBasePD { get; set; }
        public Nullable<double> LifetimeBasePDOverride { get; set; }
        public Nullable<double> Multiple_NEW { get; set; }
        public Nullable<double> LifetimeBasePPOverride { get; set; }
    
        public virtual MASTER MASTER { get; set; }
    }
}
