//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicGraphsUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALUATION
    {
        public string M_PoolID { get; set; }
        public string M_LoanID { get; set; }
        public string OriginalPropertyValue { get; set; }
        public Nullable<System.DateTime> PropertyValuationDate { get; set; }
        public Nullable<double> OriginalLTV { get; set; }
        public Nullable<double> OriginalLTFV { get; set; }
        public Nullable<double> OriginalForeclosureValue { get; set; }
        public Nullable<double> IndexedLTFV { get; set; }
        public Nullable<double> CurrentForeclosureValue { get; set; }
        public Nullable<double> CurrentPropertyValue { get; set; }
        public Nullable<double> CurrentNetPropertyValue { get; set; }
        public Nullable<decimal> ForeclosureResidualDebtEstimate { get; set; }
        public Nullable<decimal> LoanLossEstimate { get; set; }
        public Nullable<double> LoanPrice { get; set; }
    
        public virtual MASTER MASTER { get; set; }
    }
}
